vich_uploader:
  db_driver: orm
  mappings:
    music_songs:
      uri_prefix: "%app.path.music_songs%"
      upload_destination: "%kernel.project_dir%/public%app.path.music_songs%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
